### ISSUE TITLE
After installation missing command millis

### ISSUE THREAD

**Issue by FDiskas** [fatso83/dotfiles#1]
if I run `source ~/.bashrc` I got

`millis: command not found`

**Comment by fatso83** [comment]
Hi, @FDiskas! Thanks for notifying me. It's easy for stuff like this to "disappear" on personal projects.

This message means one of two things:
1. The `millis` util is not available on the `PATH`. Maybe the `PATH` variable hasn't been updated (seem strange) or the `millis` util hasn't been moved into `~/bin/`.
2. The utils weren't properly built. I think I output a small message somewhere saying you might need to run the `setup.sh` more than once, since some build tools might not be available the first time it's run.

What does `ls ~/bin` print? I have seen an issue where I have copied `millis` to a file called `~/bin` instead of putting it _into_ the directory `~/bin`, because I had forgotten to make the directory first.

**Comment by FDiskas** [comment]
Yes looks like it's a file not a directory
```
ls ~/bin
/Users/vkuciauskas/bin
```

**Comment by fatso83** [comment]
Pushed a fix. Try 
```
rm ~/bin
git pull
./setup.sh
```

**Comment by fatso83** [comment]
Thanks! I had refactored that script and introduced a bug. Should be fixed by https://github.com/fatso83/dotfiles/commit/c542d664f88371866779789facdc693c6b49280f.

```
rm ~/bin
git pull
./setup.sh
```

**Comment by fatso83** [comment]
P.S. This dotfiles repo is published as a _source of inspiration_, so I'd fork it and modify it into whatever you like, as my development setup and what apps I like probably differs from your setup. Especially the stuff in `per-host-config/` :-)
