### ISSUE TITLE
After installation i get missing command millis

### ISSUE THREAD

**Issue by erkin98** [fatso83/dotfiles#6]
`millis: command not found
This setup is missing 'direnv'. Please install it for per-directory overrides`

**Comment by fatso83** [comment]
Hi, the `millis` command is built by the `setup.sh` in the `utils` folder. In order to have that, you need to have Make, GCC, etc installed. If you inspected the output you should have seen this line: 
https://github.com/fatso83/dotfiles/blob/master/per-host-config/setup.sh#L34

> You might need to re-run the global setup as build tools might not have been available

Since I cannot know which OS you are running, this is where per-computer setups come into play, and I have added a README that says how to set that up: https://github.com/fatso83/dotfiles/tree/master/per-host-config

If you run Ubuntu 20.04 you can for instance [use my setup](https://github.com/fatso83/dotfiles/tree/master/per-host-config/ubuntu) and customize that. You can for instance see me installing the build tools here: 
https://github.com/fatso83/dotfiles/blob/master/per-host-config/ubuntu/apps.local#L16-L17

Everything in this project is quite easy to pick apart, so just inspect the output and read the setup.sh files to see what is going on. Never let code you do not understand get into your machine :)

**Comment by fatso83** [comment]
Just to be more specific, this is how you could solve it (assuming Ubuntu here):

```
cd per-host-settings
mkdir erkins-pc
cd erkins-pc
echo "apt get install g++ gcc make direnv" > setup.sh 
chmod +x setup.sh
echo 'erkins-pc' > ~/.dotfiles-machine
cd .. 
./setup.sh # runs your local per-machine setup
```

That's it. Now you just have to re-run `./setup.sh` from the top directory to get your `millis` command

**Comment by fatso83** [comment]
You can make the `setup.sh` in your per-machine directory as simple (like the previous comment) or as complex (like [my Ubuntu setup](https://github.com/fatso83/dotfiles/blob/master/per-host-config/ubuntu/setup.sh)) as you like. The point is that this directory contains the OS-specific setup you want, while the other folders contain everything that is common.

**Comment by fatso83** [comment]
@erkin98 any luck?

**Comment by fatso83** [comment]
Oh, and I forgot: the PATH is changed by . profile to include ~/bin, and that is only read once; at startup. So until you logout or restart you won't see it working unless you manually source it.

**Comment by fatso83** [comment]
No
